workspace:
  base: /go
  path: src/github.com/Oppodelldog/filediscovery

pipeline:
  build:
    image: golang:1.12.4
    commands:
      - make drone-ci

matrix:
 GO_VERSION:
   - latest
   - "1.12.4"